spring:
  application:
    name: jiguang-sdk

server:
  port: 9876

logging:
  level:
    root: debug

jiguang:
  api:
    # 此为演示数据，请替换成真实数据
    app-key: de5b45e0de18292281cbb3cf
    master-secret: 37e2077739009a532e71cce4
    dev-key: c2dc75e97486529205528b23
    dev-secret: d219e2f001df2fe4f08b6754
    group-key: 2ed1465b94aab3f03f6778e0
    group-master-secret: 5b69dce5f9dc0dabe70aa33a


